version: '2'

services:
    nginx:
        image: nginx:1.15.6
        ports:
            # 8080对应外部访问的端口,2333对应内部映射端口
            - 80:80
            - 443:443
        volumes:
            - ./dist:/home/fylder/react-webpack
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./config/cert/1887413_www.fylder.me.pem:/etc/nginx/cert/1887413_www.fylder.me.pem
            - ./config/cert/1887413_www.fylder.me.key:/etc/nginx/cert/1887413_www.fylder.me.key
        command: [nginx-debug, '-g', 'daemon off;']
        restart: always
